apiVersion: v1
kind: Secret
metadata:
  name: argocd-deploy-secret
  annotations:
    avp.kubernetes.io/path: {{ .Values.github.secretPath }} 
  labels:
    argocd.argoproj.io/secret-type: repo-creds    
data:
  sshPrivateKey: <sshPrivateKey>
  url: <url>  